name: CI

on: [push]

jobs:
  build:

    # using Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.20'

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Copy Files to Server
      run: |
        # Navega un nivel hacia arriba en la estructura de directorios
        cd ..
    
        # Ahora estás en el directorio root del servidor
    
        # Luego, ingresa a la ruta donde están las carpetas
        cd /var/www/apps/sgc/
    
        # Luego, puedes ejecutar el comando scp para copiar los archivos
        scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./dist/uts/* root@187.217.225.35:/var/www/apps/sgc/
